- name: deps
  extends: default
- name: default
  enricher:
    excludes:
      - jkube-volume-permission
      - jkube-project-label
- name: security-hardening
  enricher:
    excludes:
      - jkube-volume-permission
      - jkube-project-label
