spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: dataverse
            - name: POSTGRES_PASSWORD
              value: supersecret
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 5
            failureThreshold: 100
            periodSeconds: 5
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgres