name: Maven Unit Tests

on:
    push:
        paths:
            - "**.java"
            - "pom.xml"
            - "modules/**/pom.xml"
            - "!modules/container-base/**"
            - "!modules/dataverse-spi/**"
    pull_request:
        paths:
            - "**.java"
            - "pom.xml"
            - "modules/**/pom.xml"
            - "!modules/container-base/**"
            - "!modules/dataverse-spi/**"

jobs:
    unittest:
        name: (${{ matrix.status}} / JDK ${{ matrix.jdk }}) Unit Tests
        strategy:
            fail-fast: false
            matrix:
                jdk: [ '11' ]
                experimental: [false]
                status:  ["Stable"]
                #
                # JDK 17 builds disabled due to non-essential fails marking CI jobs as completely failed within
                # Github Projects, PR lists etc. This was consensus on Slack #dv-tech. See issue #8094
                # (This is a limitation of how Github is currently handling these things.)
                #
                #include:
                #    - jdk: '17'
                #      experimental: true
                #      status: "Experimental"
        continue-on-error: ${{ matrix.experimental }}
        runs-on: ubuntu-latest
        permissions:
            actions: write # necessary to clear and save the Maven cache
        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK ${{ matrix.jdk }}
            uses: actions/setup-java@v3
            with:
                java-version: ${{ matrix.jdk }}
                distribution: 'adopt'
          - name: Restore Maven packages from cache
            id: restore-m2-cache
            uses: actions/cache/restore@v3
            with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2

          # The reason why we use "install" here is that we want the submodules to be available in the next step.
          # Also, we can cache them this way for jobs triggered by this one.
          - name: Build with Maven
            run: > 
                mvn -B -f modules/dataverse-parent
                -Dtarget.java.version=${{ matrix.jdk }}
                -DcompilerArgument=-Xlint:unchecked -P all-unit-tests
                -pl edu.harvard.iq:dataverse -am
                install

          - name: Maven Code Coverage
            env:
                CI_NAME: github
                COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
            # The coverage commit is sometimes flaky. Don't bail out just because this optional step failed.
            continue-on-error: true
            run: >
                mvn -B
                -DrepoToken=${COVERALLS_SECRET} -DpullRequest=${{ github.event.number }}
                jacoco:report coveralls:report

          # Prepare to replace the cache. Also: we don't want to cache the WAR file, so delete it
          - id: clear-cache
            if: ${{ steps.restore-m2-cache.outputs.cache-hit }}
            continue-on-error: true # This is not crucial, just carry on
            env:
                GITHUB_TOKEN: ${{ github.token }}
            run: |
                rm -rf ~/.m2/repository/edu/harvard/iq/dataverse
                
                gh extension install actions/gh-actions-cache
                gh actions-cache delete ${{ steps.restore-m2-cache.outputs.cache-primary-key }} --confirm

          # To cache built Maven submodules, summon the save to cache action
          - name: Save Maven packages to cache
            uses: actions/cache/save@v3
            if: always() # Try to save cache, will not fail if key still exists because clean failed
            with:
                path: ~/.m2
                key: ${{ steps.restore-m2-cache.outputs.cache-primary-key }}
    push-app-img:
        name: Publish App Image
        permissions:
            contents: read
            packages: write
            pull-requests: write
        needs: unittest
        uses: ./.github/workflows/container_app_push.yml
        secrets: inherit
