name: "Shellspec"
on:
    push:
        paths:
            - tests/shell/**
            - conf/solr/**
            # add more when more specs are written relying on data
    pull_request:
        paths:
            - tests/shell/**
            - conf/solr/**
            # add more when more specs are written relying on data
jobs:
    shellcheck:
        name: Shellcheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: shellcheck
              uses: reviewdog/action-shellcheck@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review # Change reporter.
                  fail_on_error: true
                  exclude: "./tests/shell/*"
    shellspec-ubuntu:
        name: "Ubuntu"
        runs-on: ubuntu-latest
        steps:
            - name: Install shellspec
              run: curl -fsSL https://git.io/shellspec | sh -s 0.28.1 --yes
            - uses: actions/checkout@v2
            - name: Run Shellspec
              run: |
                  cd tests/shell
                  shellspec
    shellspec-centos7:
        name: "CentOS 7"
        runs-on: ubuntu-latest
        container:
            image: centos:7
        steps:
            - uses: actions/checkout@v2
            - name: Install shellspec
              run: |
                  curl -fsSL https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz | tar -xz -C /usr/share
                  ln -s /usr/share/shellspec/shellspec /usr/bin/shellspec
            - name: Install dependencies
              run: yum install -y ed
            - name: Run shellspec
              run: |
                  cd tests/shell
                  shellspec